language: php

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.4.2

env:
  global:
    - CODECOVERAGE=1
  matrix:
    - DB=mysql DB_DSN='mysql://root@127.0.0.1/test_aquila?init[]=SET sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"'

matrix:
  fast_finish: true

  include:
    - php: 7.4.2
      env: PREFER_LOWEST=1 CODECOVERAGE=0

before_install:
  - if [[ $DB == 'mysql' ]]; then mysql -u root -e 'CREATE DATABASE aquila_test;'; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE aquila_test;' -U postgres; fi

  - phpenv config-rm xdebug.ini

  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
  - echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = apcu.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'apc.enable_cli = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  - sudo locale-gen da_DK.UTF-8

install:
  - composer install --prefer-dist --no-interaction

script:
  - composer run-script check
  - composer run-script stan

notifications:
  email: false
